#!/bin/sh -e

BUILD_DIR="_build/native"

if [ ! -d ${BUILD_DIR} ]
then
	cmake \
		-G "Ninja" \
		-B ${BUILD_DIR} \
		-DCMAKE_POLICY_VERSION_MINIMUM=3.5 \
		-DCMAKE_TOOLCHAIN_FILE=cmake/linux.cmake \
		-DCMAKE_BUILD_TYPE="${BUILD_TYPE}" \
		-DCMAKE_EXPORT_COMPILE_COMMANDS=ON \
		-DCMAKE_C_COMPILER_LAUNCHER=ccache \
		-DCMAKE_CXX_COMPILER_LAUNCHER=ccache \
		./
fi

cmake --build ${BUILD_DIR}
